### PR TITLE
Fix position when scrolled. Fixes #24, fixes #11.

### LINKED ISSUE #11: Wrong position when inside paper-scroll-header-panel `content-div`
The tooltip is displays below all list elements and the tooltip is only visible for the 3rd and 4th element in the list. See screenshot:

tootip_error

Neither position:absolute nor position:fixed for the paper-tooltip fixes the offset.

### LINKED ISSUE #24: Scrolling can cause paper-tooltip's position to be wrong
http://jsbin.com/wobutexixa/1/edit?html,css,output

I believe taking into account the offsetParent's scrollTop will make this particular bug go away.

To reproduce, hover on the content div while scrolled to the bottom.

### PR DESCRIPTION
**Pull request by kevin-wise-infusionsoft**
Fixes #24 and #11 by considering scrolling when calculating position

### CODE REVIEW

**Comment by kevin-wise-infusionsoft** [comment]
@notwaldorf could you give me some idea how long it might take to merge this?  It fixes a p0 and p1 bug.

**Comment by kevinluvian** [comment]
please merge this soon

**Comment by kevinluvian** [comment]
@danbeam

**Comment by kevin-wise-infusionsoft** [comment]
I rebased this to get around a merge conflict on an extraneous comma

**Comment by kevin-wise-infusionsoft** [comment]
@danbeam @notwaldorf Any chance of getting this merged?

**Comment by notwaldorf** [comment]
@kevin-wise-infusionsoft arggggg trying to merge it now (or at least review it), but I have a merge conflict

**Comment by notwaldorf** [comment]
Hmm so the good news is that this PR doesn't break the current world, but I added the test containers in the demo and the `div#target` in the first container doesn't have a visible tooltip, while the `div#target` in the second container seems placed incorrectly, and they both depend on the _page_ scroll:

The second test example (i added some text to the `<div#target>` so i could see it, with no page scroll:
screen shot 2017-04-17 at 7 08 53


The second test example _with_ some page scroll:
screen shot 2017-04-17 at 7 09 05

**Comment by kevin-wise-infusionsoft** [comment]
Ok, I'll see what's going on

**Comment by ktiedt** [comment]
Just ran into this bug myself... whats the word on this actually getting fixed? Seems like it was so close before...

**Pull request closed without merging**
