### PR TITLE
Fixes issue #133

### PR DESCRIPTION
**Pull request by ChiragMoradiya**

### CODE REVIEW

**Comment by ChiragMoradiya** [comment]
I asked Nirmal (Who is my team mate and made commit to fix this issue) to sign CLA. It's been done now.

**Comment by ChiragMoradiya** [comment]
May I know when this request is going to be merged? 

Note:: Nirmal Baldaniya (Github: nirmalbaldaniya-dream) who had made commit in this request and Chirag Moradiya (Github: ChiragMoradiya) my self, who submitted this merge reuqest. Both has already signed Google CLAs.

Nirmal's CLA: https://cla.developers.google.com/clas/edit?id=109436054981965722701&kind=KIND_INDIVIDUAL&domain=DOMAIN_GOOGLE
Chirag's CLA:  https://cla.developers.google.com/clas/edit?id=102811669576815224384&kind=KIND_INDIVIDUAL&domain=DOMAIN_GOOGLE

**Comment by notwaldorf** [comment]
@ChiragMoradiya: if you look at the travis failures, you need to run `npm format` so that the tests can be ran and we can see if this breaks anything

cc @e111077 @bicknellr for a review

**Comment by ChiragMoradiya** [comment]
I have fixed formatting problem and pushed my change.

**Comment by e111077** [comment]
Hi it looks like there is still a formatting issue. Can you please delete your package-lock.json and your node modules, reinstall and run the formatter again?

`rm -rf package-lock.json node_modules && npm i && npm run format`

**Comment by e111077** [comment]
Ah this is a bug with our formatter that we've been encountering. I'll have a fix for you in a bit

**Comment by e111077** [comment]
fix pending on code-tailor/paper-tooltip#1

**Comment by e111077** [comment]
Release pending internal testing

**Pull request merged**
